// <auto-generated />
namespace Quinterest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class buddy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(buddy));
        
        string IMigrationMetadata.Id
        {
            get { return "201507171722407_buddy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
