// <auto-generated />
namespace Quinterest2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class shortBoardName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shortBoardName));
        
        string IMigrationMetadata.Id
        {
            get { return "201507270530107_shortBoardName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
